/** Words more than one screen uses for the same thing. */
export const commonCopy = {
  back: "Back",
  cancel: "Cancel",
  close: "Close",
  continue: "Continue",
  done: "Done",
  confirm: "Confirm",
  max: "Max",
  save: "Save",
  restore: "Restore",
  archive: "Archive",
  archived: "Archived",
  active: "Active",
  checking: "Checking...",
  unavailable: "Unavailable",
  priceUnavailable: "Price unavailable",
  amountPlaceholder: "0.00",
  copy: "Copy",
  seeAll: "See all",
  cash: "Cash",
  solana: "Solana",
  tracker: (name: string) => `${name} tracker`,
  available: (amount: string) => `Available ${amount}`,
  cashAvailable: (amount: string) => `${amount} cash available`,
  balanceUnavailable: "This token's balance cannot be shown right now. Try again in a moment.",
  tradingUnavailableOn: (network: string) =>
    `Live stock trading is unavailable on ${network}. You can explore investments, but cannot place an order here.`,
} as const;
