export { activityCopy } from "./activity.js";
export { appCopy } from "./app.js";
export { commonCopy } from "./common.js";
export { earnCopy } from "./earn.js";
export { errorsCopy } from "./errors.js";
export { fundingCopy } from "./funding.js";
export { marketsCopy } from "./markets.js";
export { networkCostCopy } from "./networkCost.js";
export { mobileOnboardingCopy, onboardingCopy } from "./onboarding.js";
export { pendingActionCopy } from "./pendingAction.js";
export { pieCopy } from "./pie.js";
export { plural } from "./plural.js";
export { portfolioCopy } from "./portfolio.js";
export { sendCopy } from "./send.js";
export { settingsCopy } from "./settings.js";
export { tradeCopy } from "./trade.js";
export { walletCopy } from "./wallet.js";
