export { activityCopy, mobileActivityCopy } from "./activity.js";
export { appCopy, mobileAppCopy } from "./app.js";
export { commonCopy } from "./common.js";
export { earnCopy, mobileEarnCopy } from "./earn.js";
export { errorsCopy, mobileErrorsCopy } from "./errors.js";
export { fundingCopy, mobileFundingCopy } from "./funding.js";
export { marketsCopy, mobileMarketsCopy } from "./markets.js";
export { networkCostCopy } from "./networkCost.js";
export { mobileOnboardingCopy, onboardingCopy } from "./onboarding.js";
export { mobilePendingActionCopy, pendingActionCopy } from "./pendingAction.js";
export { mobilePieCopy, pieCopy } from "./pie.js";
export { plural } from "./plural.js";
export { mobilePortfolioCopy, portfolioCopy } from "./portfolio.js";
export { mobileSendCopy, sendCopy } from "./send.js";
export { mobileSettingsCopy, settingsCopy } from "./settings.js";
export { mobileTradeCopy, tradeCopy } from "./trade.js";
export { mobileWaitingCopy, waitingCopy } from "./waiting.js";
export { mobileWalletCopy, walletCopy } from "./wallet.js";
