/** Finding trackers, their prices and a tracker's own page. */
export const marketsCopy = {
  title: "Search",
  desktopTitle: "Markets",
  eyebrow: "Explore",
  lead: "Tokenized stock trackers. Live display prices are indicative; the trade price appears at review.",
  searchPlaceholder: "Company or ticker",
  searchLabel: "Search investments",
  tickerLabel: "Live market ticker",
  results: (count: number) => `${count} results`,
  noMatch: "No matching investment.",
  noMatches: "No matching investments.",
  groups: {
    movers: "Top movers",
    index: "Funds and ETFs",
    companies: "Companies",
    watchlist: "My watchlist",
  },
  categories: {
    all: "All",
    companies: "Companies",
    index: "Funds and ETFs",
    watchlist: "My watchlist",
  },
  dayChange: "24h change",
  moversWaiting: "Top movers appear when current prices load.",
  moverLine: (symbol: string) => `${symbol} · 24h`,
  browseAll: "Browse all",
  categoriesLabel: "Market categories",
  nothingHere: "Nothing here yet.",
  atReview: "At review",
  noLivePrice: "No live price",
  liveIndicative: "Live indicative",
  issuerLine: (symbol: string, issuer: string | undefined) => `${symbol} · ${issuer ?? ""}`,
  assets: (count: number) => `${count} assets`,
  columns: {
    asset: "Asset",
    price: "Price",
    day: "24h",
    week: "1W history",
    trade: "Trade",
  },
  sorted: (descending: boolean) => (descending ? "↓" : "↑"),
  buy: "Buy",
  view: "View",
  showMore: (remaining: number) => `Show more (${remaining} left)`,
  watchToggle: (watched: boolean, symbol: string) =>
    `${watched ? "Remove" : "Add"} ${symbol} ${watched ? "from" : "to"} watchlist`,

  chooser: {
    results: (label: string) => `${label} results`,
    option: (action: string, name: string) => `${action} ${name}`,
    more: (hidden: number) => `${hidden} more. Type a name or ticker to narrow it down.`,
  },

  chart: {
    loading: "Loading history",
  },

  detail: {
    notFound: "No such investment.",
    backToSearch: "Back to search",
    search: "Search",
    watch: (watched: boolean) => (watched ? "Remove from watchlist" : "Add to watchlist"),
    priceUnavailable: "Current price unavailable",
    past24h: "past 24h",
    liveNote: "Live indicative price. Your order quote is confirmed at review.",
    quoteNote: "Your order price comes from a live quote at review.",
    historyLabel: "Price history",
    loadingHistory: "Loading price history...",
    noChart: (range: string) => `No verified ${range} chart available.`,
    historySource: "Historical prices · Jupiter",
    yourHolding: "Your holding",
    holdingValue: (value: string) => `${value} indicative value`,
    valueWaiting: "Value available when a current price loads",
    notOwned: "You do not own this tracker yet.",
    about: "About",
    aboutTracker: (symbol: string, name: string) =>
      `${symbol} is an xStocks tracker certificate that follows ${name}. It is not a direct company or ETF share and gives no voting rights.`,
    issuerControl:
      "The issuer can freeze, move or burn these tokens without your signature. Trades, amounts and timing are visible on chain.",
    dividends:
      "Dividends are not paid out in cash. The issuer reinvests them by raising a multiplier on the token, so the balance shown here grows instead. Stock splits change the balance the same way.",
    retired: (symbol: string) =>
      `${symbol} is no longer offered to buy here. What you hold can still be sold or sent.`,
    retiredShort: (symbol: string) => `${symbol} is no longer offered to buy here.`,
    retiredMobile: "No longer offered to buy.",
    issuerDetails: "Read issuer details",
    tradePanel: "Trade panel",
    tradeDirection: "Trade direction",
    startInvesting: "Start investing",
    createWalletFirst: "Create a wallet before placing an order.",
    createPortfolioFirst: "Create a portfolio before placing an order.",
    createWallet: "Create a wallet to invest",
    createPortfolio: "Create portfolio",
    buy: "Buy",
    sell: "Sell",
    tradeTitle: (side: "buy" | "sell", name: string) =>
      `${side === "buy" ? "Buy" : "Sell"} ${name} tracker`,
  },
} as const;
