import type { PortfolioIconGlyph, PortfolioIconTint } from "../domain/portfolioIcon.js";
import { plural } from "./plural.js";

const noDayChange = "No live day change available";
const createToStart = "Create a portfolio to start investing.";
const activityEmpty = "Money moves and trades appear here.";

/** Home, a portfolio's own screen, and creating, naming and funding portfolios. */
export const portfolioCopy = {
  home: {
    title: "Home",
    eyebrow: "Overview",
    addMoney: "Add money",
    findStocks: "Find stocks",
    summaryLabel: "Wallet summary",
    totalValue: "Total value",
    dayIndicative: "24h indicative",
    heldDayIndicative: "held assets · 24h indicative",
    noDayChange,
    invested: "Invested",
    heldTrackers: "Held trackers",
    cashToInvest: "Cash to invest",
    acrossPortfolios: "Across portfolios",
    earning: "Earning",
    apy: (rate: string) => `${rate}% variable APY`,
    apyUnavailable: "Current APY unavailable",
    viewApy: "View current APY in Earn",
    notAvailable: "N/A",
    waitingForValues: "Waiting for current balances or market prices",
    excludesEarn: "Excludes money in Earn, which could not be read yet",
    valueUnavailable: "Value unavailable",
    yourInvestments: "Your investments",
    assets: (count: number) => `${count} assets`,
    columns: {
      asset: "Asset",
      units: "Units",
      price: "Price",
      day: "24h",
      value: "Value",
      allocation: "Alloc.",
      week: "1W",
      portfolio: "Portfolio",
      investments: "Investments",
      cash: "Cash",
    },
    atReview: "At review",
    share: (percent: string) => `${percent}%`,
    noInvestments: "No investments yet. ",
    exploreMarkets: "Explore markets",
    portfolios: "Portfolios",
    newPortfolio: "New portfolio",
    new: "New",
    pie: "Pie",
    createToStart,
    watchlist: "Watchlist",
    viewMarkets: "View markets",
    watchlistEmpty: "Save trackers to find them here.",
    recentActivity: "Recent activity",
    seeAll: "See all",
    activityEmpty,
    marketLists: "Market lists",
    shelves: {
      watchlist: "My watchlist",
      stocks: "Stocks",
      index: "Index trackers",
    },
    earn: "Earn",
    watchlistEmptyMobile: "Your watchlist is empty.",
    findInvestments: "Find investments",
    archivedPortfolios: "Archived portfolios",
    restore: (label: string) => `Restore ${label}`,
  },

  earnPromo: {
    eyebrow: "Earn · Jupiter Lend",
    rate: (rate: string) => `${rate}%`,
    apy: "APY",
    couldBeEarning: "Your cash could be earning",
    couldEarn: (cash: string, yearly: string) =>
      `Your ${cash} in cash could earn about ${yearly} a year.`,
    waitingCash: "Cash that is waiting to be invested can earn in the meantime.",
    start: "Start earning",
    footnote: "Variable rate, shown as of now. Lending carries risk.",
  },

  holdings: {
    noInvestments: "No investments yet",
    findTracker: "Find a company or index tracker to get started.",
    search: "Search investments",
    tokens: (amount: string) => `${amount} tokens`,
    line: (symbol: string, amount: string) => `${symbol} · ${amount}`,
    liveValue: "Live value",
    balanceConfirmed: "Balance confirmed",
    title: "Holdings",
    titleInPie: "Cash and other holdings",
    empty: "Nothing here yet. Move money into this portfolio to get started.",
    sell: "Sell",
  },

  card: {
    pie: (stocks: number) => `Pie · ${plural(stocks, "stock")}`,
    investments: (count: number) => plural(count, "investment"),
    noInvestments: "No investments yet",
    valueUnavailable: "Value unavailable",
  },

  detail: {
    allPortfolios: "All portfolios",
    pie: "Pie",
    portfolio: "Portfolio",
    created: (date: string) => `Created ${date}`,
    value: "Portfolio value",
    valueUnavailable: "Value unavailable",
    cashToInvest: (amount: string) => `${amount} USDC cash to invest`,
    moveMoneyHere: "Move money here",
    invest: "Invest",
    buy: "Buy an investment",
    rebalance: "Rebalance",
    receive: "Receive",
    send: "Send",
    settings: "Portfolio settings",
    archivedTitle: "This portfolio is archived.",
    archivedLead:
      "It stays visible and its history is kept, but it is hidden from the portfolio list.",
    recentActivity: "Recent activity",
    nothingMoved: "Nothing has moved yet. Fund or receive into this portfolio to begin.",
    advancedAddress: "Advanced portfolio address",
    copyAddress: "Copy address",
  },

  settings: {
    title: "Portfolio settings",
    nameLabel: "Portfolio name",
    restoreTitle: "Restore this portfolio",
    archiveTitle: "Archive this portfolio",
    archiveLead:
      "It disappears from the portfolio list. Nothing is deleted and you can restore it at any time.",
  },

  create: {
    titlePortfolio: "New portfolio",
    titlePie: "New pie",
    kindsLabel: "What to create",
    kinds: {
      portfolio: { title: "Portfolio", description: "Buy one investment at a time." },
      pie: { title: "Pie", description: "Set a mix of stocks and invest in all of them at once." },
    },
    lead: "Give it a name only you see. The name never leaves this browser.",
    nameLabel: "Portfolio name",
    namePlaceholder: "Investing",
    suggestions: ["Investing", "Long term", "Everyday"],
    creating: "Creating portfolio...",
    submit: "Create portfolio",
    pieLead:
      "A pie is its own portfolio with its own address. Investing splits your money across the mix.",
    pieSubmit: "Create pie",
    pieCreating: "Creating pie...",
  },

  icon: {
    label: "Icon and color",
    change: "Change",
    icon: "Icon",
    color: "Color",
    usePieRing: "Use the pie ring",
    glyphOption: (name: string) => `${name} icon`,
    tintOption: (name: string) => `${name} color`,
    glyphs: {
      compass: "General",
      target: "Goal",
      flag: "Milestone",
      mountains: "Ambition",
      house: "Home",
      graduation: "Education",
      airplane: "Travel",
      heart: "Personal",
      shield: "Steady",
      clock: "Long term",
      globe: "Global",
      tree: "Nature",
      sun: "Energy",
      lightning: "Growth",
      "chart-line": "Markets",
      "chart-pie": "Diversified",
      buildings: "Property",
      factory: "Industry",
      heartbeat: "Healthcare",
      flask: "Research",
      cpu: "Chips",
      robot: "Automation",
      cloud: "Software",
      wifi: "Connectivity",
      car: "Mobility",
      truck: "Logistics",
      shopping: "Consumer",
      coins: "Income",
      briefcase: "Business",
      scales: "Balance",
      bank: "Finance",
      diamond: "Quality",
    } satisfies Record<PortfolioIconGlyph, string>,
    tints: {
      neutral: "Neutral",
      sage: "Sage",
      blue: "Blue",
      lilac: "Lilac",
      clay: "Clay",
      ochre: "Ochre",
      teal: "Teal",
      rose: "Rose",
    } satisfies Record<PortfolioIconTint, string>,
  },

  observer: {
    eyebrow: "Privacy posture",
    noLabel: "No owner label onchain",
    standalone:
      "This portfolio appears as a standalone address, without your name or its NoirWire label.",
    publicTitle: "Public onchain",
    copyAddress: "Copy portfolio address",
    publicNote: "Balances and activity on this address are public.",
    visible: "Balances, asset tickers, transfers, trades, amounts, and timing are visible.",
    privateTitle: "Not written onchain",
    privateItems: [
      "Your local portfolio name",
      "Its relationship to your funding wallet",
      "Which other NoirWire portfolios you control",
    ],
    relayed:
      "These stay in this browser. Balance reads and trades are relayed by NoirWire's server, so the network provider, Jupiter and MagicBlock see this address but never your IP address. The relay stores and logs nothing; you have to trust it not to.",
    relayer:
      "When NoirWire's relayer pays a network cost for this portfolio, that transaction names the relayer, so an observer can tell this address uses NoirWire. It does not name your funding wallet or your other portfolios.",
    clue: "Funding can still create a clue. Reusing a known address or moving a distinctive amount moments later may let an observer infer a connection.",
  },

  receive: {
    title: "Receive",
    lead: (portfolio: string, network: string) =>
      `${portfolio}'s own address on ${network}, derived from your recovery phrase.`,
    mainnet: " Only send Solana assets to it. Funds sent from another network are lost.",
    testNetwork: " It holds devnet assets only, so never send mainnet funds to it.",
    copyAddress: "Copy address",
    copyDescribe: "Copy portfolio address",
    publicNote:
      "A transfer straight to this address is public and ties the sender to this portfolio. Use the private funding flow to move value in from your own funding balance instead.",
  },

  addMoney: {
    title: "Add money",
    arrived: (amount: string) =>
      `${amount} USDC has arrived in your funding wallet. Move it to a portfolio before buying.`,
    moveTo: (portfolio: string) => `Move money to ${portfolio}`,
    stepGet: (network: string) => `1. Get USDC on ${network}`,
    stepGetDetail: (network: string) =>
      `Buy it on an exchange you already use and withdraw it on the ${network} network. USDC is all you need: network costs are a few cents and are paid out of it.`,
    stepSend: "2. Send it to your funding address",
    stepSendDetail: "This first transfer is public and may link the sending address to you.",
    depositAddress: "Get your USDC deposit address",
    onlyUsdc: (network: string) =>
      `Only send USDC on ${network}. Other assets or networks may be lost.`,
    copyAddress: "Copy address",
    copyDescribe: "Copy funding address",
    stepMove: "3. Move USDC into a portfolio privately",
    stepMoveDetail:
      "Once it arrives, move it in through the private route so it is not linked to a portfolio on chain.",
    footnote:
      "Moving USDC privately has a service fee and may take time to arrive. Trades stay public.",
  },

  notFound: {
    message: "That portfolio does not exist.",
    back: "Back to portfolios",
  },
} as const;
